import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ApiProvider } from "@/lib/api-context";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Stack AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <ApiProvider>{children}</ApiProvider>
        <Toaster />
      </body>
    </html>
  );
}
